SELECT 
    df.LABEL,
    SUM(f.POPULARITY_VALUE) AS TOTAL_POPULARITY
FROM FACT_FOOD_TRENDS f
JOIN DIM_FOOD df ON f.FOOD_KEY = df.FOOD_KEY
WHERE f.TREND_TYPE_KEY = 1
GROUP BY df.LABEL
ORDER BY TOTAL_POPULARITY DESC
LIMIT 10;

SELECT 
    df.CATEGORY,
    AVG(f.POPULARITY_VALUE) AS AVG_POPULARITY,
    COUNT(DISTINCT df.FOOD_KEY) AS FOOD_COUNT
FROM FACT_FOOD_TRENDS f
JOIN DIM_FOOD df ON f.FOOD_KEY = df.FOOD_KEY
WHERE f.TREND_TYPE_KEY = 1
GROUP BY df.CATEGORY
ORDER BY AVG_POPULARITY DESC;

SELECT 
    df.LABEL || ' + ' || dcf.COOC_LABEL AS COMBINATION,
    SUM(f.POPULARITY_VALUE) AS TOTAL_POPULARITY
FROM FACT_FOOD_TRENDS f
JOIN DIM_FOOD df ON f.FOOD_KEY = df.FOOD_KEY
JOIN DIM_COOC_FOOD dcf ON f.COOC_FOOD_KEY = dcf.COOC_FOOD_KEY
WHERE f.TREND_TYPE_KEY = 2
GROUP BY COMBINATION
ORDER BY TOTAL_POPULARITY DESC
LIMIT 10;

SELECT 
    d.MONTH_NAME,
    f.LABEL,
    SUM(ft.POPULARITY_VALUE) AS POPULARITY
FROM FACT_FOOD_TRENDS ft
JOIN DIM_FOOD f ON ft.FOOD_KEY = f.FOOD_KEY
JOIN DIM_DATE d ON ft.DATE_KEY = d.DATE_KEY
WHERE ft.TREND_TYPE_KEY = 1
GROUP BY 1, 2
ORDER BY 3 DESC
LIMIT 50;

SELECT d.QUARTER, f.LABEL AS FOOD, cf.COOC_LABEL AS COOC_FOOD, SUM(ft.POPULARITY_VALUE) AS TOTAL_POP
FROM FACT_FOOD_TRENDS ft
JOIN DIM_FOOD f ON ft.FOOD_KEY = f.FOOD_KEY
JOIN DIM_COOC_FOOD cf ON ft.COOC_FOOD_KEY = cf.COOC_FOOD_KEY
JOIN DIM_DATE d ON ft.DATE_KEY = d.DATE_KEY
WHERE ft.TREND_TYPE_KEY = 2
GROUP BY d.QUARTER, FOOD, COOC_FOOD
ORDER BY d.QUARTER, TOTAL_POP DESC;
