USE WAREHOUSE TERMITE_WH;
USE DATABASE TERMITE_DB;
USE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA PUBLIC;

-- Staging: FOODS
CREATE OR REPLACE TABLE STG_FOODS AS
SELECT * 
FROM FOOD_ANALYTICS_AND_FOOD_TRENDS_DATA_IN_WEB_RECIPES.PUBLIC.FOODS;

-- Staging: TOP_FINAL
CREATE OR REPLACE TABLE STG_TOP_FINAL AS
SELECT * 
FROM FOOD_ANALYTICS_AND_FOOD_TRENDS_DATA_IN_WEB_RECIPES.PUBLIC.TOP_FINAL;

-- Staging: TOP_COOC_FINAL
CREATE OR REPLACE TABLE STG_TOP_COOC_FINAL AS
SELECT * 
FROM FOOD_ANALYTICS_AND_FOOD_TRENDS_DATA_IN_WEB_RECIPES.PUBLIC.TOP_COOC_FINAL;

-- LOAD
USE SCHEMA TERMITE_DB.PUBLIC;

-- DIM_DATE
CREATE OR REPLACE TABLE DIM_DATE AS
WITH months AS (
    SELECT 1 AS month_num, 'M1' AS month_code, 'January' AS month_name
    UNION ALL SELECT 2, 'M2', 'February'
    UNION ALL SELECT 3, 'M3', 'March'
    UNION ALL SELECT 4, 'M4', 'April'
    UNION ALL SELECT 5, 'M5', 'May'
    UNION ALL SELECT 6, 'M6', 'June'
)
SELECT 
    ROW_NUMBER() OVER (ORDER BY month_num) AS DATE_KEY,
    2024 AS YEAR,
    month_num AS MONTH,
    CEIL(month_num / 3.0) AS QUARTER,
    month_code AS MONTH_CODE,
    month_name AS MONTH_NAME
FROM months;

-- DIM_FOOD
CREATE OR REPLACE TABLE DIM_FOOD AS
SELECT DISTINCT
    ROW_NUMBER() OVER (ORDER BY FOODID) AS FOOD_KEY,
    FOODID,
    LABEL,
    COALESCE(CATEGORY, 'Unknown') AS CATEGORY,
    SR,
    URI
FROM TERMITE_DB.STAGING.STG_FOODS
WHERE FOODID IS NOT NULL;

-- DIM_COOC_FOOD
CREATE OR REPLACE TABLE DIM_COOC_FOOD AS
SELECT DISTINCT
    ROW_NUMBER() OVER (ORDER BY c.COOC_FOOD_ID) AS COOC_FOOD_KEY,
    c.COOC_FOOD_ID,
    c.LABEL AS COOC_LABEL,
    COALESCE(f.CATEGORY, 'Unknown') AS COOC_CATEGORY
FROM TERMITE_DB.STAGING.STG_TOP_COOC_FINAL c
LEFT JOIN TERMITE_DB.STAGING.STG_FOODS f 
    ON c.COOC_FOOD_ID = f.FOODID
WHERE c.COOC_FOOD_ID IS NOT NULL;

-- DIM_TREND_TYPE
CREATE OR REPLACE TABLE DIM_TREND_TYPE AS
SELECT 1 AS TREND_TYPE_KEY, 'SINGLE' AS TREND_TYPE, 'Individual food popularity' AS DESCRIPTION
UNION ALL
SELECT 2, 'CO_OCCURRENCE', 'Food combination popularity';

-- FACT_FOOD_TRENDS
CREATE OR REPLACE TABLE FACT_FOOD_TRENDS AS
WITH unpivoted_single AS (
    SELECT 
        s.FOOD_ID,
        NULL AS COOC_FOOD_ID,
        1 AS TREND_TYPE_KEY,
        d.DATE_KEY,
        CASE d.MONTH_CODE
            WHEN 'M1' THEN s.M1
            WHEN 'M2' THEN s.M2
            WHEN 'M3' THEN s.M3
            WHEN 'M4' THEN s.M4
            WHEN 'M5' THEN s.M5
            WHEN 'M6' THEN s.M6
        END AS POPULARITY_VALUE,
        s.SCORE,
        s.TOP_ORDER
    FROM TERMITE_DB.STAGING.STG_TOP_FINAL s
    CROSS JOIN DIM_DATE d
),
unpivoted_cooc AS (
    SELECT 
        c.FOOD_ID,
        c.COOC_FOOD_ID,
        2 AS TREND_TYPE_KEY,
        d.DATE_KEY,
        CASE d.MONTH_CODE
            WHEN 'M1' THEN c.M1
            WHEN 'M2' THEN c.M2
            WHEN 'M3' THEN c.M3
            WHEN 'M4' THEN c.M4
            WHEN 'M5' THEN c.M5
            WHEN 'M6' THEN c.M6
        END AS POPULARITY_VALUE,
        c.SCORE,
        c.TOP_ORDER
    FROM TERMITE_DB.STAGING.STG_TOP_COOC_FINAL c
    CROSS JOIN DIM_DATE d
),
combined AS (
    SELECT * FROM unpivoted_single
    UNION ALL
    SELECT * FROM unpivoted_cooc
),
with_analytics AS (
    SELECT
        c.*,
        f.FOOD_KEY,
        cf.COOC_FOOD_KEY,
        ROW_NUMBER() OVER (
            PARTITION BY c.DATE_KEY, c.TREND_TYPE_KEY 
            ORDER BY c.POPULARITY_VALUE DESC
        ) AS RANK_IN_MONTH,
        LAG(c.POPULARITY_VALUE) OVER (
            PARTITION BY c.FOOD_ID, c.TREND_TYPE_KEY 
            ORDER BY c.DATE_KEY
        ) AS PREV_POPULARITY,
        SUM(c.POPULARITY_VALUE) OVER (
            PARTITION BY c.FOOD_ID, c.TREND_TYPE_KEY 
            ORDER BY c.DATE_KEY 
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS CUMULATIVE_POPULARITY
    FROM combined c
    JOIN DIM_FOOD f ON c.FOOD_ID = f.FOODID
    LEFT JOIN DIM_COOC_FOOD cf ON c.COOC_FOOD_ID = cf.COOC_FOOD_ID
)
SELECT
    ROW_NUMBER() OVER (ORDER BY DATE_KEY, FOOD_KEY) AS TREND_KEY,
    FOOD_KEY,
    COALESCE(COOC_FOOD_KEY, -1) AS COOC_FOOD_KEY,
    DATE_KEY,
    TREND_TYPE_KEY,
    POPULARITY_VALUE,
    SCORE,
    TOP_ORDER,
    RANK_IN_MONTH,
    CASE 
        WHEN PREV_POPULARITY IS NULL OR PREV_POPULARITY = 0 THEN NULL
        ELSE ((POPULARITY_VALUE - PREV_POPULARITY) / PREV_POPULARITY) * 100
    END AS POPULARITY_CHANGE_PCT,
    CUMULATIVE_POPULARITY
FROM with_analytics
WHERE POPULARITY_VALUE IS NOT NULL;

DESCRIBE TABLE FOOD_ANALYTICS_AND_FOOD_TRENDS_DATA_IN_WEB_RECIPES.PUBLIC.FOODS;